# Generated by Django 5.0.7 on 2024-08-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('long_description', models.CharField(max_length=500)),
                ('photo', models.URLField(max_length=1000, null=True)),
                ('video', models.URLField(max_length=1000, null=True)),
                ('usd_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='System_Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Minimum', 'Minimum'), ('Recommended', 'Recommended')], max_length=20)),
                ('os', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('memory', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
            ],
        ),
    ]
