# Generated by Django 5.0.7 on 2024-08-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='System_Requirements',
            new_name='SystemRequirements',
        ),
    ]
