# Generated by Django 5.0.7 on 2024-08-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_long_description_alter_game_pegi_rating_and_more'),
        ('misc', '0004_alter_platform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ManyToManyField(to='misc.developer'),
        ),
    ]
