# Generated by Django 5.0.7 on 2024-08-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_developer'),
        ('misc', '0004_alter_platform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(to='misc.platform'),
        ),
    ]
