# Generated by Django 5.0.7 on 2024-08-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_platform'),
        ('misc', '0005_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='misc.genre'),
        ),
    ]
