# Generated by Django 5.0.7 on 2024-08-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_genres'),
        ('misc', '0006_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='features',
            field=models.ManyToManyField(to='misc.feature'),
        ),
    ]
