# Generated by Django 5.0.7 on 2024-08-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_alter_game_badges'),
        ('misc', '0008_alter_developer_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='badges',
            field=models.ManyToManyField(to='misc.badges'),
        ),
    ]
