# Generated by Django 5.0.7 on 2024-08-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_alter_game_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemrequirement',
            name='graphics',
            field=models.CharField(default=1, max_length=1500),
            preserve_default=False,
        ),
    ]
