# Generated by Django 5.1 on 2024-09-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_fix_attribute_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemrequirement',
            name='memory',
        ),
        migrations.AddField(
            model_name='systemrequirement',
            name='memorys',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemrequirement',
            name='storage',
            field=models.IntegerField(),
        ),
    ]
