# Generated by Django 5.1 on 2024-09-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_remove_systemrequirement_memory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemrequirement',
            old_name='memorys',
            new_name='memory_mb',
        ),
    ]
