# Generated by Django 5.1 on 2024-09-25 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_alter_game_long_description_alter_game_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='game',
            name='video',
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(blank=True, max_length=1000)),
                ('video', models.URLField(blank=True, max_length=1000)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
