# Generated by Django 5.1 on 2024-09-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_remove_game_photo_remove_game_video_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='photo',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='media',
            name='video',
        ),
    ]
