# Generated by Django 5.1 on 2024-09-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_rename_photo_media_url_remove_media_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('documents', 'Documents')], null=True),
        ),
    ]
