# Generated by Django 5.1 on 2024-10-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_media_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='type',
            new_name='kind',
        ),
    ]
