# Generated by Django 5.1 on 2024-10-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_rename_type_media_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='kind',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('documents', 'Documents')], default=1),
            preserve_default=False,
        ),
    ]
