version: '3.0'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file: ".env"
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "56379:6379"

volumes:
  postgres_data:

