# Generated by Django 5.0.7 on 2024-08-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(choices=[('Usa', 'Usa'), ('France', 'France'), ('Germany', 'Germany'), ('Japan', 'Japan'), ('China', 'China'), ('Uk', 'Uk'), ('Russian', 'Russian'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('still_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(choices=[('Usa', 'Usa'), ('France', 'France'), ('Germany', 'Germany'), ('Japan', 'Japan'), ('China', 'China'), ('Uk', 'Uk'), ('Russian', 'Russian'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('still_active', models.BooleanField(default=True)),
            ],
        ),
    ]
