# Generated by Django 5.0.7 on 2024-08-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Playstation', 'Playstation'), ('Xbox', 'Xbox'), ('Nintendo', 'Nintendo')], max_length=100),
        ),
    ]
