# Generated by Django 5.0.7 on 2024-08-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_alter_platform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='entity',
            field=models.CharField(choices=[('Person', 'Person'), ('Company', 'Company'), ('Unknown', 'Unknown')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Playstation', 'Playstation'), ('Xbox', 'Xbox'), ('Nintendo', 'Nintendo'), ('Unknown', 'Unknown')], default='Unknown', max_length=100),
        ),
    ]
