# Generated by Django 5.0.7 on 2024-08-28 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='submitted_review',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
