name: Test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pixel_vault_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 55432:5432

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12.4

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.8.2

      - name: Install packages
        run: poetry install

      - name: Wait for PostgreSQL
        run: until pg_isready -h 127.0.0.1 -p 55432; do sleep 1; done

      - name: Load environment variables
        run: |
          set -o allexport
          source .pytest_env
          set +o allexport

      - name: List files in the repository
        run: ls -R

      - name: Run Tests
        run: poetry run pytest
